'use strict';
const cfg=window.CLINIC_CONFIG, live=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&!location.hostname.endsWith('.github.io'));
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',user=null,staff=false,tab='appointments',busy=false;
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(n));
const sessionLabel=s=>new Date(s.starts_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})+' IST';
const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);
const demo={slots:[{id:'demo-slot',starts_at:tomorrow.toISOString(),capacity:4}],appointments:[],records:[],invoices:[],messages:[]};
async function api(path,options={}){const r=await fetch(cfg.supabaseUrl+path,{...options,headers:{apikey:cfg.supabaseAnonKey,Authorization:'Bearer '+(token||cfg.supabaseAnonKey),'Content-Type':'application/json',...(options.headers||{})}});const body=await r.text();let data;try{data=JSON.parse(body)}catch{data=null}if(!r.ok)throw new Error(data?.message||data?.msg||data?.error_description||'Request failed. Please try again.');return data;}
async function rows(table){if(!live)return staff?demo[table]:demo[table].filter(r=>r.patient_id===user.id&&(table!=='records'||r.shared));if(table==='records'&&staff)return api('/rest/v1/rpc/staff_records',{method:'POST',body:'{}'});const fields=table==='records'?'id,appointment_id,patient_id,summary,shared,created_at':'*';return api('/rest/v1/'+table+'?select='+fields+'&order=created_at.desc');}
async function insert(table,row){if(live)return api('/rest/v1/'+table,{method:'POST',body:JSON.stringify(row)});const item={...row,id:crypto.randomUUID(),created_at:new Date().toISOString()};demo[table].unshift(item);return [item];}
async function patch(table,id,row){if(live)return api('/rest/v1/'+table+'?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(row)});Object.assign(demo[table].find(x=>x.id===id),row);}
function status(id,text){if($(id))$(id).textContent=text;}
function formData(form){return Object.fromEntries(new FormData(form));}
function button(text,action,id){return `<button type="button" data-action="${action}" data-id="${esc(id)}">${text}</button>`;}
async function loadSlots(){if(!$('#slot-select'))return;try{const slots=live?await api('/rest/v1/slots?select=*&active=eq.true&starts_at=gte.'+encodeURIComponent(new Date().toISOString())+'&order=starts_at.asc'):demo.slots;$('#slot-select').innerHTML='<option value="">Choose a session</option>'+slots.map(s=>`<option value="${esc(s.id)}">${esc(sessionLabel(s))}${live?'':' · sample session'}</option>`).join('');if(!slots.length)$('#slot-select').innerHTML='<option value="">No sessions published — contact the clinic</option>';}catch(e){$('#slot-select').innerHTML='<option value="">Sessions unavailable — contact the clinic</option>';status('#booking-result',e.message);}}
if($('#booking-mode'))$('#booking-mode').textContent='No sign-in needed. WhatsApp opens with your request; press Send there. The clinic confirms by replying.';
if($('#booking-form'))$('#booking-form input[name=preferred_date]').min=date();
if($('#privacy-mode'))$('#privacy-mode').textContent=live?'Your session is kept in memory and ends when this page reloads. Sign out when finished.':'This preview stores sample entries only in this tab’s memory. It is not connected to the clinic.';
function renderAccount(){if(user){$('#account').innerHTML=`<div class="toolbar"><strong>${staff?'Staff workspace':'Patient account'}</strong><span>${esc(user.email)}</span><button id="signout">Sign out</button></div>`;$('#signout').onclick=async()=>{if(live)try{await api('/auth/v1/logout',{method:'POST'})}catch{}token='';user=null;staff=false;renderAccount();$('#portal-content').innerHTML='';};renderPortal();return;}
$('#account').innerHTML=`<div class="account-grid"><form id="login" class="panel"><h3>${live?'Sign in to your account':'Explore the working preview'}</h3>${live?'<label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="current-password"></label><div class="toolbar"><button class="button" type="submit">Sign in</button><button type="button" id="signup">Create patient account</button></div>':'<p class="notice">Use fictional data only. Preview roles demonstrate workflows without granting access to clinic data.</p><div class="toolbar"><button type="button" id="demo-patient">Patient preview</button><button type="button" id="demo-staff">Staff preview</button></div>'}<p id="auth-result" role="status"></p></form><aside><p class="eyebrow" style="color:#ffaddc">YOUR PATIENT PORTAL</p><h3>A smoother visit.<br>A clearer next step.</h3><p>Track requests and confirmations, read shared visit summaries, view bills, and send the clinic a message.</p><p>Staff can schedule visits, keep clinical notes and record payments through their authorised accounts.</p></aside></div>`;
if(!live){for(const role of ['patient','staff'])$('#demo-'+role).onclick=()=>{user={id:'demo-patient',email:'preview@example.test'};staff=role==='staff';renderAccount();};return;}
$('#login').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(formData(e.target))});token=data.access_token;user=data.user;staff=(await api('/rest/v1/staff?select=user_id&user_id=eq.'+encodeURIComponent(user.id))).length>0;renderAccount();}catch(err){token='';user=null;status('#auth-result',err.message)}finally{busy=false}};
$('#signup').onclick=async()=>{const f=$('#login');if(!f.reportValidity())return;try{await api('/auth/v1/signup',{method:'POST',body:JSON.stringify(formData(f))});status('#auth-result','Account requested. Check your email to confirm your account, then sign in.')}catch(err){status('#auth-result',err.message)}};
}
if($('#booking-form'))$('#booking-form').onsubmit=e=>{
 e.preventDefault();const f=formData(e.target);
 const number=String(cfg.whatsappNumber||'').replace(/[^0-9]/g,'');
 if(!/^[1-9][0-9]{9,14}$/.test(number)){status('#booking-result','WhatsApp booking will be available once the clinic confirms its WhatsApp number. Please call +91 93694 63570 to request a visit.');return;}
 if(f.preferred_date<date()){status('#booking-result','Please choose today or a future date.');return;}
 const hindi=window.ClinicLanguage?.language==='hi';
 const message=hindi?['नमस्ते डॉ. ए. खान क्लिनिक, मुझे अपॉइंटमेंट लेना है।','नाम: '+f.name,'मोबाइल: '+f.phone,'परामर्श: '+window.ClinicLanguage.t(f.service),'पसंदीदा तारीख: '+f.preferred_date,'पसंदीदा समय: '+f.preferred_time+' (भारतीय समय)','कृपया उपलब्धता और परामर्श शुल्क की पुष्टि करें।'].join('\n'):['Hello Dr. A. Khan clinic, I would like to request an appointment.','Name: '+f.name,'Mobile: '+f.phone,'Visit: '+f.service,'Preferred date: '+f.preferred_date,'Preferred time: '+f.preferred_time+' IST','Please confirm availability and the consultation fee.'].join('\n');
 const url='https://wa.me/'+number+'?text='+encodeURIComponent(message);
 status('#booking-result','Press Send in WhatsApp to submit your request. Your appointment is confirmed only after the clinic replies.');
 window.open(url,'_blank','noopener');
 const fallback=document.createElement('a');fallback.href=url;fallback.target='_blank';fallback.rel='noopener';fallback.textContent='Open WhatsApp';$('#booking-result').append(document.createTextNode(' '),fallback);
};

$('#staff-link').onclick=()=>{if(!user&&!live)status('#auth-result','Choose Staff preview to explore the dashboard. In production, staff permissions are granted in the backend.');};
async function renderPortal(){if(!user)return;const root=$('#portal-content');root.innerHTML='<p role="status">Loading your workspace…</p>';try{const [appointments,records,invoices,messages,slots]=await Promise.all([rows('appointments'),rows('records'),rows('invoices'),rows('messages'),live?api('/rest/v1/slots?select=*&order=starts_at.asc'):demo.slots]);const names={appointments:'Appointments',records:staff?'Patient records':'Visit summaries',invoices:'Billing',messages:'Messages',...(staff?{schedule:'Schedule'}:{})};root.innerHTML=`<div class="toolbar">${Object.entries(names).map(([key,name])=>`<button data-tab="${key}" class="${tab===key?'active':''}">${name}</button>`).join('')}</div><div class="dashboard"><div class="stats"><div class="stat"><b>${appointments.filter(a=>a.status==='requested').length}</b><span>Pending requests</span></div><div class="stat"><b>${appointments.filter(a=>a.status==='confirmed').length}</b><span>Confirmed visits</span></div><div class="stat"><b>${money(invoices.filter(i=>i.status==='unpaid').reduce((n,i)=>n+Number(i.amount),0))}</b><span>Outstanding invoices</span></div></div><div id="workspace"></div><p id="workspace-result" role="status"></p></div>`;
root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderPortal()});const work=$('#workspace');const patientOptions=appointments.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} · ${esc(a.service)} · ${esc(a.status)}</option>`).join('');
if(tab==='appointments'){work.innerHTML=appointments.length?`<div class="table-wrap"><table><thead><tr><th>PATIENT</th><th>VISIT</th><th>SESSION</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${appointments.map(a=>`<tr><td>${esc(a.name)}<br><small>${esc(a.phone)}</small></td><td>${esc(a.service)}</td><td>${esc(slots.find(s=>s.id===a.slot_id)?sessionLabel(slots.find(s=>s.id===a.slot_id)):'Session unavailable')}</td><td><span class="badge">${esc(a.status)}</span></td><td>${staff?`${['requested','confirmed'].includes(a.status)?button('Cancel','cancel',a.id):''}${a.status==='requested'?button('Confirm','confirm',a.id):''}${a.status==='confirmed'?button('Complete','complete',a.id):''}`:['requested','confirmed'].includes(a.status)?button('Cancel request','cancel-patient',a.id):''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No appointments yet. Request your first visit above.</div>';}
if(tab==='records'){work.innerHTML=(staff?`<form id="record-form" class="panel"><h3>Add a visit record</h3><label>Appointment<select name="appointment_id" required>${patientOptions}</select></label><label>Private clinical notes<textarea name="private_notes" required maxlength="10000"></textarea></label><label>Patient-visible summary<textarea name="summary" maxlength="5000"></textarea></label><label class="check"><input type="checkbox" name="shared"> Share this summary with the patient</label><button class="button">Save record</button></form>`:'')+records.map(r=>`<article class="record"><span class="muted">${esc(new Date(r.created_at).toLocaleDateString('en-IN'))}</span><h3>Visit summary</h3><p>${esc(r.summary||'No summary shared.')}</p>${staff?`<h4>Private clinical notes</h4><p>${esc(r.private_notes)}</p><span class="badge">${r.shared?'Summary shared':'Staff only'}</span>`:''}</article>`).join('')+(records.length?'':'<p class="empty">No visit records available.</p>');if(staff)$('#record-form').onsubmit=async e=>{e.preventDefault();const f=formData(e.target),a=appointments.find(a=>a.id===f.appointment_id);await mutate(()=>insert('records',{...f,patient_id:a.patient_id,shared:f.shared==='on'}));};}
if(tab==='invoices'){work.innerHTML=(staff?`<form id="invoice-form" class="panel"><h3>Create invoice</h3><label>Appointment<select name="appointment_id" required>${patientOptions}</select></label><label>Description<input name="description" required maxlength="200" placeholder="Consultation"></label><label>Amount (₹)<input name="amount" type="number" required min="1" max="1000000" step="0.01"></label><button class="button">Create invoice</button></form>`:'')+invoices.map(i=>`<article class="record"><span class="muted">Invoice ${esc(i.id.slice(0,8).toUpperCase())} · ${esc(new Date(i.created_at).toLocaleDateString('en-IN'))}</span><h3>${money(i.amount)}</h3><p>${esc(i.description)}</p><span class="badge">${esc(i.status)}</span><p>${esc(i.payment_method||'Payment to be arranged with the clinic')}${i.payment_reference?' · '+esc(i.payment_reference):''}</p><div class="toolbar">${button('Print invoice','print',i.id)}${staff&&i.status==='unpaid'?button('Record payment','pay',i.id):''}${!staff&&i.status==='unpaid'&&/^https:\/\//.test(cfg.paymentLink)?`<a class="button" href="${esc(cfg.paymentLink)}" target="_blank" rel="noopener">Pay via clinic provider ↗</a>`:''}</div><div id="pay-${esc(i.id)}"></div></article>`).join('')+(invoices.length?'':'<p class="empty">No invoices yet.</p>');if(staff)$('#invoice-form').onsubmit=async e=>{e.preventDefault();const f=formData(e.target),a=appointments.find(a=>a.id===f.appointment_id);await mutate(()=>insert('invoices',{...f,amount:Number(f.amount),patient_id:a.patient_id,status:'unpaid'}));};}
if(tab==='messages'){work.innerHTML=`<form id="message-form" class="panel"><h3>${staff?'Send a patient message':'Message the clinic'}</h3>${staff?`<label>Patient appointment<select name="appointment_id" required>${patientOptions}</select></label>`:''}<label>Message<textarea name="body" required maxlength="3000" placeholder="For appointment and follow-up questions. This inbox is not monitored for emergencies."></textarea></label><button class="button">Send message</button></form>`+messages.map(m=>`<article class="record"><span class="muted">${m.from_staff?'Clinic':'Patient'} · ${esc(new Date(m.created_at).toLocaleString('en-IN'))}</span><p>${esc(m.body)}</p></article>`).join('');$('#message-form').onsubmit=async e=>{e.preventDefault();const f=formData(e.target);if(live&&!staff){await mutate(()=>api('/rest/v1/rpc/send_patient_message',{method:'POST',body:JSON.stringify({p_body:f.body})}));}else{await mutate(()=>insert('messages',{body:f.body,patient_id:staff?appointments.find(a=>a.id===f.appointment_id).patient_id:user.id,from_staff:staff}));}};}
if(tab==='schedule'&&staff){work.innerHTML=`<form id="slot-form" class="panel"><h3>Publish a consultation session</h3><p class="muted">All session times are in India Standard Time. Capacity limits confirmed appointments; requests may exceed capacity.</p><label>Date<input name="day" type="date" min="${date()}" required></label><label>Time (IST)<input name="time" type="time" required></label><label>Capacity<input name="capacity" type="number" min="1" max="100" value="1" required></label><button class="button">Publish session</button></form>`+slots.map(s=>`<article class="record"><b>${esc(sessionLabel(s))}</b><p>Capacity: ${s.capacity} · ${s.active===false?'Closed':'Open'}</p>${s.active===false?'':button('Close session','close-slot',s.id)}</article>`).join('');$('#slot-form').onsubmit=async e=>{e.preventDefault();const f=formData(e.target);await mutate(()=>insert('slots',{starts_at:new Date(f.day+'T'+f.time+':00+05:30').toISOString(),capacity:Number(f.capacity),active:true}));await loadSlots()};}
root.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const {action,id}=b.dataset;if(action==='print'){const invoice=b.closest('.record');const title=document.title;document.title='Dr A Khan invoice '+id.slice(0,8);document.querySelectorAll('.record').forEach(r=>r.hidden=r!==invoice);window.print();document.querySelectorAll('.record').forEach(r=>r.hidden=false);document.title=title;return}if(action==='pay'){const div=document.getElementById('pay-'+id);div.innerHTML='<form class="panel"><label>Method<select name="payment_method"><option>Cash</option><option>UPI</option><option>Card terminal</option></select></label><label>Reference (required for UPI / card)<input name="payment_reference" maxlength="100"></label><button class="button">Confirm verified receipt</button></form>';div.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=formData(e.target);if(f.payment_method!=='Cash'&&!f.payment_reference.trim()){status('#workspace-result','Enter the verified transaction reference.');return}await mutate(()=>patch('invoices',id,{...f,status:'paid',paid_at:new Date().toISOString()}));};return}if(action==='close-slot'){await mutate(()=>patch('slots',id,{active:false}));await loadSlots();return}if(action==='cancel-patient'&&live){await mutate(()=>api('/rest/v1/rpc/cancel_appointment',{method:'POST',body:JSON.stringify({p_id:id})}));return}await mutate(()=>patch('appointments',id,{status:({confirm:'confirmed',cancel:'cancelled','cancel-patient':'cancelled',complete:'completed'})[action]}));});
}catch(err){root.innerHTML='<p class="notice" role="alert">'+esc(err.message)+'</p>';}}
async function mutate(fn){if(busy)return;busy=true;try{await fn();await renderPortal()}catch(err){status('#workspace-result',err.message)}finally{busy=false}}
if($('#account'))renderAccount();loadSlots();
const whatsapp=String(cfg.whatsappNumber||'').replace(/[^0-9]/g,'');
if(/^[1-9][0-9]{9,14}$/.test(whatsapp)){const link=document.createElement('a');link.className='whatsapp-float';link.href='https://wa.me/'+whatsapp+'?text='+encodeURIComponent('Hello Dr. A. Khan clinic, I would like information about a consultation.');link.target='_blank';link.rel='noopener';link.textContent='WhatsApp the clinic ↗';document.body.append(link);const contact=document.createElement('a');contact.className='whatsapp-inline';contact.href=link.href;contact.target='_blank';contact.rel='noopener';contact.textContent='Chat on WhatsApp ↗';if($('.contact-card'))$('.contact-card').append(contact);}else{const note=document.createElement('button');note.className='whatsapp-inline';note.type='button';note.textContent='WhatsApp the clinic ↗';note.onclick=()=>{note.textContent='WhatsApp number awaiting confirmation. Call +91 93694 63570.';};if($('.contact-card'))$('.contact-card').append(note);}
