'use strict';
// Manual UPI requests never mark a payment as verified or a visit as confirmed.
function manualUpiRequest(patient,settings,now=new Date(),id=crypto.randomUUID()){
 const preview=settings.preview===true,amount=Number(patient.amount),upi=preview?'Dummy UPI ID — not payable':String(settings.upiId||'').trim(),payee=String(settings.payeeName||'').trim();
 const whatsapp=String(settings.summaryWhatsappNumber||cfg.whatsappNumber||'').replace(/[^0-9]/g,'');
 if((!preview&&!/^[a-zA-Z0-9._-]{2,256}@[a-zA-Z0-9.-]{2,64}$/.test(upi))||!payee||!Number.isFinite(amount)||amount<=0||amount>100000||!/^\d+(?:\.\d{1,2})?$/.test(String(patient.amount))||!/^[1-9][0-9]{9,14}$/.test(whatsapp))throw Error('Payment details are not configured. Please contact the clinic.');
 const record={payment_request_id:'AK'+id.replaceAll('-','').toUpperCase(),created_at:now.toISOString(),patient_name:patient.name.trim(),patient_phone:patient.phone.trim(),payment_purpose:patient.purpose,clinic_reference:String(patient.clinic_reference||'').trim(),expected_amount_inr:amount,payee_upi:upi,payee_name:payee,payment_reference:'',demo:preview,payment_status:preview?'demo_not_paid':'awaiting_manual_verification'};
 const params=new URLSearchParams({pa:upi,pn:payee,am:amount.toFixed(2),cu:'INR',tn:record.payment_request_id,tr:record.payment_request_id});
 return {record,whatsapp,uri:preview?null:'upi://pay?'+params.toString().replaceAll('+','%20')};
}
function manualUpiSummary(record){
 return [record.demo?'DEMO PAYMENT RECORD — NO PAYMENT TAKEN':'MANUAL UPI PAYMENT RECORD','Payment request ID: '+record.payment_request_id,'Patient name: '+record.patient_name,'Mobile: '+record.patient_phone,'Purpose: '+record.payment_purpose,'Clinic reference: '+(record.clinic_reference||'Not provided'),'Expected amount (INR): '+record.expected_amount_inr.toFixed(2),'Recipient: '+record.payee_name,'UPI ID: '+record.payee_upi,'UPI reference (patient supplied): '+record.payment_reference,record.demo?'Payment: DEMO — NOT PAID':'Payment: AWAITING MANUAL VERIFICATION'].join('\n');
}
function showManualUpi(patient){
 let request;try{request=manualUpiRequest(patient,cfg.manualUpi);}catch(error){status('#payment-details-result',error.message);return;}
 const {record,uri,whatsapp}=request,booking=$('#payment-details-form');
 $('#manual-upi-panel')?.remove();const panel=document.createElement('section');panel.id='manual-upi-panel';panel.className='panel manual-upi-panel';panel.setAttribute('aria-labelledby','manual-upi-title');
 panel.innerHTML=`<div class="form-heading"><p class="eyebrow">PAY THE CLINIC</p><h2 id="manual-upi-title" tabindex="-1">Pay with UPI.</h2><p>Pay in your UPI app, then return here to share your transaction reference.</p></div><div class="upi-amount"><span>Payment amount</span><strong data-no-translate>${esc(money(record.expected_amount_inr))}</strong></div><dl class="upi-details"><div><dt>Patient</dt><dd data-no-translate>${esc(record.patient_name)}</dd></div><div><dt>Purpose</dt><dd data-no-translate>${esc(record.payment_purpose)}</dd></div><div><dt>Recipient</dt><dd data-no-translate>${esc(record.payee_name)}</dd></div><div><dt>UPI ID</dt><dd data-no-translate>${esc(record.payee_upi)}</dd></div><div><dt>Payment request ID</dt><dd data-no-translate>${esc(record.payment_request_id)}</dd></div></dl>${record.demo?'<p class="notice">Demo recipient only. No payment can be made until the clinic adds its real UPI ID.</p><button type="button" class="button upi-pay" disabled>UPI payment not active yet</button>':'<a class="button upi-pay" href="'+esc(uri)+'">Open UPI app ↗</a>'}<p class="upi-help">If your app does not open, copy the UPI ID and pay in your preferred app. Check the recipient name and amount before paying. Return to this tab after payment.</p><button type="button" class="upi-secondary" id="copy-upi-id" ${record.demo?'disabled':''}>Copy UPI ID</button><div class="upi-verification"><span class="status-dot"></span><span>${record.demo?'Demo — no payment taken':'Awaiting payment verification'}</span></div><form id="upi-reference-form"><label>UPI transaction reference / UTR<input name="payment_reference" required pattern="[A-Za-z0-9-]{6,64}" minlength="6" maxlength="64" autocomplete="off" placeholder="Reference from your payment app"></label><p class="upi-help">Enter the reference shown in your payment app. The clinic will check its bank account before confirming payment.</p><button class="button" type="submit">Send details on WhatsApp ↗</button><button type="button" class="upi-secondary" id="download-payment-record">Download request record</button><p class="upi-help">WhatsApp opens with your details. Press Send there to share them with the clinic.</p></form><button type="button" class="upi-secondary" id="edit-upi-booking">Edit payment details</button><p id="upi-result" role="status"></p>`;
 booking.hidden=true;booking.after(panel);$('#manual-upi-title').focus();
 $('#copy-upi-id').onclick=async()=>{try{await navigator.clipboard.writeText(record.payee_upi);status('#upi-result','UPI ID copied.');}catch{status('#upi-result','Select and copy the UPI ID displayed above.');}};
 $('#edit-upi-booking').onclick=()=>{panel.remove();booking.hidden=false;booking.querySelector('input').focus();};
 function updateReference(){const form=$('#upi-reference-form');if(!form.reportValidity())return false;record.payment_reference=form.elements.payment_reference.value.trim();return true;}
 $('#upi-reference-form').onsubmit=e=>{e.preventDefault();if(!updateReference())return;const url='https://wa.me/'+whatsapp+'?text='+encodeURIComponent(manualUpiSummary(record));window.open(url,'_blank','noopener');status('#upi-result',record.demo?'Your demo summary is ready in WhatsApp. No payment has been taken.':'Your details are ready in WhatsApp. Payment is awaiting verification by the clinic.');const fallback=document.createElement('a');fallback.href=url;fallback.target='_blank';fallback.rel='noopener';fallback.textContent='Open WhatsApp';$('#upi-result').append(document.createTextNode(' '),fallback);};
 $('#download-payment-record').onclick=()=>{if(!updateReference())return;const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=record.payment_request_id+'-request.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('#upi-result','Request record downloaded. This is not a payment receipt.');};
}
if($('#payment-details-form'))$('#payment-details-form').onsubmit=e=>{e.preventDefault();if(!cfg.manualUpi?.enabled){status('#payment-details-result','Online UPI payment details will be available here soon. Please contact the clinic.');return;}showManualUpi(formData(e.target));};
